<a href="https://colab.research.google.com/github/vc14/COMP572_NeuralNetworks/blob/main/DataCheck_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

This is a synthetic customer dataset created for practicing Exploratory Data Analysis (EDA), feature engineering, and machine learning (ANN, regression/classification).
It simulates a subscription-based company (like telecom, SaaS, or online retail) and contains messy, real-world–like data with missing values, outliers, rare categories, and text notes.
The target is churned → whether the customer has left (1) or is still active (0).

In [ ]:
import pandas as pd
df=pd.read_csv('eda_sample_customers.csv', parse_dates=['signup_date'])
df.head()

,customer_id,signup_date,age,income,gender,city,has_car,purchases_last_6m,avg_session_mins,credit_score,satisfaction,referral_source,zip_code,notes,churned
0,174,2025-02-21,41.0,291.98,Female,Glenwood,No,2,12.24,310.0,4,Friend,95608.0,likes new app,0
1,275,2023-09-28,46.0,913.25,Male,Oakdale,No,1,7.93,309.0,4,Email,92689.0,legacy plan,0
2,491,2023-11-09,NaN,615.03,Female,Lakeside,No,3,5.98,341.0,4,Search,96342.0,asked for refund,0
3,73,2024-09-08,55.0,864.29,Male,Oakdale,No,0,19.41,421.0,3,Friend,93763.0,prefers SMS,0
4,306,2022-07-17,35.0,103.98,Female,Glenwood,Yes,5,9.85,300.0,2,Friend,90306.0,moved recently,0

In [ ]:
# Checking, how many rows/columns and what the columns are.
df.shape, df.columns.tolist()

((505, 15),
 ['customer_id',
  'signup_date',
  'age',
  'income',
  'gender',
  'city',
  'has_car',
  'purchases_last_6m',
  'avg_session_mins',
  'credit_score',
  'satisfaction',
  'referral_source',
  'zip_code',
  'notes',
  'churned'])

In [ ]:
# data types + where missing values exist.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        505 non-null    int64
 1   signup_date        505 non-null    datetime64[ns]
 2   age                490 non-null    float64
 3   income             484 non-null    float64
 4   gender             487 non-null    object
 5   city               505 non-null    object
 6   has_car            505 non-null    object
 7   purchases_last_6m  505 non-null    int64
 8   avg_session_mins   493 non-null    float64
 9   credit_score       493 non-null    float64
 10  satisfaction       505 non-null    int64
 11  referral_source    495 non-null    object
 12  zip_code           502 non-null    float64
 13  notes              505 non-null    object
 14  churned            505 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(4), object(5)
memory usage: 59.3+ KB

In [ ]:
# A fast overview of numeric stats and categorical counts/top category.
df.describe(include='all').T.head(20)

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
customer_id,505.0,NaN,NaN,NaN,249.514851,1.0,124.0,250.0,374.0,500.0,144.612098
signup_date,505,NaN,NaN,NaN,2022-09-20 02:51:05.346534400,2020-01-11 00:00:00,2021-04-20 00:00:00,2022-10-01 00:00:00,2024-02-06 00:00:00,2025-06-28 00:00:00,NaN
age,490.0,NaN,NaN,NaN,34.544898,-1.0,27.0,35.0,41.0,120.0,11.350298
income,484.0,NaN,NaN,NaN,475.044628,61.65,244.0825,368.635,551.2,5361.49,501.184249
gender,487,4,Male,228,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,505,7,Lakeside,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_car,505,3,Yes,288,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchases_last_6m,505.0,NaN,NaN,NaN,1.90495,0.0,1.0,2.0,3.0,8.0,1.577016
avg_session_mins,493.0,NaN,NaN,NaN,12.540101,0.0,8.66,12.17,15.64,63.68,6.060126
credit_score,493.0,NaN,NaN,NaN,350.687627,300.0,309.0,341.0,374.0,850.0,58.464775
satisfaction,505.0,NaN,NaN,NaN,3.407921,1.0,3.0,3.0,4.0,5.0,1.170036
referral_source,495,6,Search,196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zip_code,502.0,NaN,NaN,NaN,93458.603586,90024.0,91616.0,93477.0,95134.5,96998.0,2000.860581
notes,505,19,called support twice,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
churned,505.0,NaN,NaN,NaN,0.148515,0.0,0.0,0.0,0.0,1.0,0.355962

In [ ]:
# know how many exact duplicate rows you have
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(5)

In [ ]:
# Printing duplicates including the firts occurence
duplicate_rows=df[df.duplicated(keep=False)]
duplicate_rows

,customer_id,signup_date,age,income,gender,city,has_car,purchases_last_6m,avg_session_mins,credit_score,satisfaction,referral_source,zip_code,notes,churned
23,336,2023-05-18,31.0,190.56,Male,Riverton,Yes,1,7.35,336.0,3,Other,92924.0,called support twice,0
37,336,2023-05-18,31.0,190.56,Male,Riverton,Yes,1,7.35,336.0,3,Other,92924.0,called support twice,0
46,34,2022-01-13,43.0,680.04,Male,Springfield,Yes,2,7.12,383.0,1,Ads,94097.0,loves coupons,0
93,254,2021-05-12,38.0,142.48,Female,Lakeside,No,1,12.67,339.0,4,Search,95089.0,legacy plan,1
98,41,2022-05-27,26.0,656.23,Female,Springfield,No,0,11.99,415.0,3,Search,93373.0,VIP customer,0
213,254,2021-05-12,38.0,142.48,Female,Lakeside,No,1,12.67,339.0,4,Search,95089.0,legacy plan,1
234,90,2022-10-02,21.0,NaN,Male,Lakeside,No,1,9.58,348.0,3,Search,91466.0,called support twice,0
392,41,2022-05-27,26.0,656.23,Female,Springfield,No,0,11.99,415.0,3,Search,93373.0,VIP customer,0
462,90,2022-10-02,21.0,NaN,Male,Lakeside,No,1,9.58,348.0,3,Search,91466.0,called support twice,0
496,34,2022-01-13,43.0,680.04,Male,Springfield,Yes,2,7.12,383.0,1,Ads,94097.0,loves coupons,0

In [ ]:
# Drop duplicates
df=df.drop_duplicates()
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(0)